version: 1.0.{build}

os:
- WMF 5

install:
- git submodule update --init --recursive

build_script:
- ps: write-host "no need to build powershell"

test_script:
- ps: scripts/lib/test.appveyor.ps1 -path "./beam"